AWSTemplateFormatVersion: '2010-09-09'
Description: "Create Lambda to send billing information."
Parameters:
  Bucketname:
    Type: String
    Description: S3Bucketname
  Filepass:
    Type: String
    Description: S3Filepass
  Topicarn:
    Type: String
    Description: SNSTopicarn
Resources:
  BillingIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Lambda-send-billing-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Path: /
      Policies:
      - PolicyName: Lambda-send-billing-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - ce:*
            - sns:CreateTopic
            - sns:Publish
            Resource: '*'
  BillingFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref Bucketname
        S3Key: !Ref Filepass
      Description: 'send billing information'
      FunctionName: 'send-billing-info'
      Handler: 'index.lambda_handler'
      Runtime: 'python3.8'
      Timeout: 30
      Environment:
        Variables:
          Topic: !Ref Topicarn
      Role: !GetAtt
        - BillingIamRole
        - Arn
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      Description: "ScheduledRule"
      ScheduleExpression: 'cron(0 0 * * ? *)'
      State: ENABLED
      Targets:
      - Arn: !GetAtt
        - 'BillingFunction'
        - 'Arn'
        Id: 'TargetFunctionV1'
  PermissionForEventsToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: !Ref "BillingFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "ScheduledRule"
          - "Arn"